title: Jacob Franz # your name (or website title) here
logo: "/assets/images/cropped_profile_picture.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring backend java developer
  <br><br>
  <a href="https://github.com/polyglitch">View My GitHub Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
