title: Jacob Franz # your name (or website title) here
logo: "https://github.com/polyglitch.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Jacob Franz is a skilled associate developer whose ability to collaborate with others,
persistence, and flexibility ensure that he can be an important part of any team. Jacob Franz
has a bachelor’s degree in Computer Science and Scientific Applications from Tennessee
Technological University. Jacob primarily used Java throughout college and extremely
comfortable writing in it. He has extensive experience both leading and working in teams from
both Nashville Event Lighting as a crew chief and in Boy Scouts where he obtained the rank of
Eagle Scout. Jacob enjoys the problem solving and cooperative nature of programming.
  <br><br>
  <a href="https://github.com/polyglitch">View My GitHub Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
